runtime: python311
instance_class: F4_1G
env: standard
service: default

# 4 concurrent worker processes max, global IP with fixed port
entrypoint: gunicorn --worker-class uvicorn.workers.UvicornWorker --workers 4 --bind=0.0.0.0:8080 main:app

automatic_scaling:
  min_instances: 0
  max_instances: 2

# handlers:
# - url: /soc
#   static_dir: data
#   secure: always
#   script: auto
