runtime: python311
instance_class: F4_1G
env: standard
service: default    # PROD FastAPI service

entrypoint: gunicorn -b 0.0.0.0:8080 -w 8 -k uvicorn.workers.UvicornWorker main:app

automatic_scaling:
  min_instances: 0
  max_instances: 5
