"""This module provides functionality for building and running ClassifAI as a REST API service.

This allows a user to call the search methods of one or more `VectorStore` objects,
from an API endpoint.

These functions interact with the ClassifAI Indexer module's `VectorStore` objects,
such that their `embed`, `search` and `reverse_search` methods are exposed as
REST API endpoints, as a FastAPI service started with these functions.

Full API documentation for FastAPI endpoints and Pydantic Models
can be found in autogenerated app Swagger docs at `/docs`.
To do this without providing your own data, run the initial demo to make a test
`VectorStore` with `/DEMO/general_workflow_demo.ipynb`
then run it as a demo server at `/DEMO/general_workflow_serve.py`.
"""

from .main import get_router, get_server, make_endpoints, run_server

__all__ = ["get_router", "get_server", "make_endpoints", "run_server"]
